title: Sergei Tikhomirov
description: Blockchain Researcher
url: https://s-tikhomirov.github.io
baseurl: ""

permalink: /:title/

theme: minima

header_pages:
  - index.md
  - publications.md
  - talks.md
  - writing.md

show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed
  - jekyll-sitemap

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - plan
